project:
  type: book

book:
  title: "Gifi Analysis of Multivariate Data"
  author: "Jan de Leeuw"
  date: "5/5/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

date: last-modified
date-format: long
bibliography: [mypubs.bib, total.bib]
number-sections: true
pdf-engine: lualatex
keep-tex: true
format:
   pdf:
    documentclass: scrreprt
    fontsize: 12pt
    include-in-header: 
     - preamble.tex
    keep-tex: true
    link-citations: true
   html:
    theme:
      - cosmo
      - brand
    fontsize: 12pt
toc: true
toc-depth: 3
editor: source
papersize: letter
graphics: true
link-citations: true
mainfont: Times New Roman




