project:
  type: book

book:
  title: "Homogeneity Analysis"
  author: "Jan de Leeuw"
  date: "5/5/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - coding.qmd
    - algorithm.qmd
    - mca.qmd
    - references.qmd
date: last-modified
date-format: long
bibliography: [mypubs.bib, total.bib]
number-sections: true
fontsize: 12pt
link-citations: true
toc: true
toc-depth: 3
editor: source
papersize: letter
graphics: true
mainfont: Times New Roman
search: true
cover-image: hom_cover.jpg
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    fontsize: 12pt
    include-in-header: 
     - preamble.tex
    pdf-engine: lualatex
    keep-tex: true
 

 





